/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Description = string;
export type Hashtag = string;
export interface ImagePrompt {
  'bottomText' : string,
  'topText' : string,
  'imagePrompt' : string,
}
export interface PinterestPinContent {
  'titles' : Array<Title>,
  'hashtags' : Array<Array<Hashtag>>,
  'originalUrl' : string,
  'timeRecommendations' : Array<TimeRecommendation>,
  'descriptions' : Array<Description>,
  'imagePrompts' : Array<ImagePrompt>,
}
export interface TimeRecommendation {
  'region' : string,
  'time' : string,
  'typeOfDay' : string,
}
export type Title = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'generatePins' : ActorMethod<[string], PinterestPinContent>,
  'getAllGeneratedPins' : ActorMethod<[], Array<PinterestPinContent>>,
  'getGeneratedPinsByUrl' : ActorMethod<[string], PinterestPinContent>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];